In [1]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence

# Load IMDB dataset
num_words = 10000  # Number of words to keep from the dataset
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=num_words)

# Pad sequences to a fixed length
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

embedding_vector_length = 32

model = Sequential()
model.add(Embedding(num_words, embedding_vector_length, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

batch_size = 64
num_epochs = 3

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=num_epochs, batch_size=batch_size)

17464789/17464789 [==============================] - 0s 0us/step
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 32)           320000    
                                                                 
 lstm (LSTM)                 (None, 100)               53200     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 373301 (1.42 MB)
Trainable params: 373301 (1.42 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/3
391/391 [==============================] - 454s 1s/step - loss: 0.4421 - accuracy: 0.7894 - val_loss: 0.3179 - val_accuracy: 0.8678
Epoch 2/3
391/391 [==============================] - 450s 1s/step - loss

In [1]:
import numpy as np
def sigmoid(x):
  return 1/(1+np.exp(-x))
def tanh(x):
  return np.tanh(x)
def relu(x):
  return np.maximum(0,x)
def lalty_relu(x,alpha=0.01):
  return np.maximum(alpha*x,x)
def softmax(x):
  exp_x=np.exp(x)
  return exp_x/np.sum(exp_x)
x=np.array([-1,0,1])
print(sigmoid(x))
print(tanh(x))
print(relu(x))
print(lalty_relu(x))
print(softmax(x))

[0.26894142 0.5        0.73105858]
[-0.76159416  0.          0.76159416]
[0 0 1]
[-0.01  0.    1.  ]
[0.09003057 0.24472847 0.66524096]


In [2]:
!pip install nbconvert

In [ ]:
! jupyter nbconvert --to html